CREATE TABLE User
(
	UserID VARCHAR(75) NOT NULL,
	Rating INTEGER NOT NULL,
	Location VARCHAR(50) DEFAULT NULL,
	Country VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (UserID)
) ENGINE = INNODB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE Item
(
	ItemID INTEGER NOT NULL,
	Name VARCHAR(100) NOT NULL,
	Currently DECIMAL(8, 2) NOT NULL,
	Buy_Price DECIMAL(8, 2),
	First_Bid DECIMAL(8, 2) NOT NULL,
	Number_Of_Bids INTEGER NOT NULL,
	Start TIMESTAMP NOT NULL,
	End TIMESTAMP NOT NULL,
	Seller VARCHAR(75),
	Description VARCHAR(4000),
	PRIMARY KEY (ItemID),
	FOREIGN KEY (Seller) REFERENCES User(UserID)
) ENGINE = INNODB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE Category
(
	CategoryID INTEGER NOT NULL,
	Name VARCHAR(30),
	PRIMARY KEY (CategoryID)
) ENGINE = INNODB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE Categorize
(
	ItemID INTEGER NOT NULL,
	CategoryID INTEGER NOT NULL,
	PRIMARY KEY (ItemID, CategoryID),
	FOREIGN KEY (ItemID) REFERENCES Item(ItemID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (CategoryID) REFERENCES Category(CategoryID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = INNODB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE Bid
(
	Bidder VARCHAR(75) NOT NULL,
	ItemID INTEGER NOT NULL,
	Time TIMESTAMP NOT NULL,
	Amount DECIMAL(8, 2) NOT NULL,
	PRIMARY KEY (Bidder, Time),
	FOREIGN KEY (ItemID) REFERENCES Item(ItemID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (Bidder) REFERENCES User(UserID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = INNODB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;